# Generated by Django 3.2.3 on 2021-05-17 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_auto_20210516_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fechaEntrevista',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 19, 0, 15, 139857)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 19, 0, 15, 139857)),
        ),
    ]
