# Generated by Django 3.2.3 on 2021-05-18 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_auto_20210516_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fechaEntrevista',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 56, 34, 480421)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 56, 34, 480421)),
        ),
    ]
