# Generated by Django 3.2.3 on 2021-05-18 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210518_0056'),
        ('empresa', '0004_alter_empresa_usuario'),
        ('candidato', '0005_auto_20210518_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fechaEntrevista',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 33, 13, 32224), verbose_name='Fecha de entrevista'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 33, 13, 32224), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='Referencia persona'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.vacante', verbose_name='Vacante a la que aplica'),
        ),
    ]
