# Generated by Django 3.2.3 on 2021-05-18 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0008_auto_20210518_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fechaEntrevista',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 35, 19, 212118), verbose_name='Fecha de entrevista'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fechaRegistro',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 35, 19, 212118), verbose_name='Fecha de registro'),
        ),
    ]
