# Generated by Django 3.2.3 on 2021-05-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ap_materno',
            field=models.CharField(max_length=30, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ap_paterno',
            field=models.CharField(max_length=30, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=14, verbose_name='Telefono o celular'),
        ),
    ]
