# Generated by Django 3.2 on 2021-05-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPersona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ap_materno',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ap_paterno',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
    ]
