# Generated by Django 3.2 on 2021-05-15 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1)),
                ('correo', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='Persona relacionada con la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Relacion de la vacante con la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criterio', models.CharField(max_length=255)),
                ('puntuacion', models.IntegerField()),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.vacante', verbose_name='Relacion de los criterios con la vacante')),
            ],
        ),
    ]
