# Generated by Django 3.2.3 on 2021-05-18 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210518_0056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_auto_20210516_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Referencia usuario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.CharField(max_length=255, verbose_name='Correo de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='Referencia persona'),
        ),
    ]
