# Generated by Django 3.2.3 on 2021-05-18 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0003_auto_20210516_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='fechaActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 56, 34, 481420)),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 56, 34, 481420)),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fechaActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 56, 34, 482421)),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 56, 34, 482421)),
        ),
    ]
