# Generated by Django 3.2.3 on 2021-05-18 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_empresa_usuario'),
        ('candidato', '0006_auto_20210518_0133'),
        ('entrevista', '0004_auto_20210518_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestaentrevista',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidato.candidato', verbose_name='Candidato'),
        ),
        migrations.AlterField(
            model_name='contestaentrevista',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrevista.entrevista', verbose_name='Entrevista'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='fechaActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 33, 13, 33225)),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 33, 13, 33225)),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.vacante', verbose_name='Vacante'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.entrevista', verbose_name='Entrevista'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fechaActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 33, 13, 34225)),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 33, 13, 34225)),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='contesta_entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrevista.contestaentrevista', verbose_name='Contestado por'),
        ),
    ]
